version: '3'
services:
  backend:
    image: stivetedom/my_backend_image:latest
    environment:
      - WS_BACK_URL=http://backend:5000/
    ports:
      - "5000:5000"

  frontend:
    image: stivetedom/my_frontend_image:latest
    environment:
      - WS_BACK_URL=http://backend:5000/
    ports:
      - "8080:80"
